fix: r13y debugging
Signed-off-by: Austin Seipp <aseipp@pobox.com>

diff --git a/.github/workflows/r13y.yml b/.github/workflows/r13y.yml
--- a/.github/workflows/r13y.yml
+++ b/.github/workflows/r13y.yml
@@ -8,7 +8,7 @@ on:
 
 jobs:
   build:
-    name: "nightly: Reproducibility check"
+    name: "check: Reproducibility fuzzing"
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -54,9 +54,11 @@ jobs:
           echo "Done."
 
           # now exit _after_ we're done doing reports
-          (compgen -G "/tmp/diffoscope-reports/*" >/dev/null) && exit 1
+          if compgen -G "/tmp/diffoscope-reports/*" >/dev/null; then
+            exit 1
+          fi
       - name: Upload R13Y reports
-        if: failure() # always runs if previous step fails
+        if: failure() # only runs if previous step fails
         uses: actions/upload-artifact@v3
         with:
           name: r13y-reports
