feat: attempt to produce diff reports
Signed-off-by: Austin Seipp <aseipp@pobox.com>

diff --git a/.github/workflows/reproducible.yml b/.github/workflows/reproducible.yml
--- a/.github/workflows/reproducible.yml
+++ b/.github/workflows/reproducible.yml
@@ -25,8 +25,28 @@ jobs:
           #!/usr/bin/env bash
           exec >&2
           echo "For derivation \$3 (tmpdir = \$4):"
-          exec /nix/var/nix/profiles/default/bin/diffoscope --text - "\$1" "\$2"
+          exec /nix/var/nix/profiles/default/bin/diffoscope --text /tmp/report.txt "\$1" "\$2"
           EOF
           chmod +x diff-hook.sh && sudo mv diff-hook.sh /etc/nix/diff-hook.sh
       - name: Build world, normally
         run: nix build .#world
+      - name: Iterate and rebuild, one at a time
+        run: |
+          while read -r line; do
+            attr=$(cat "result/$line")
+            echo "R13Y test of $attr (repeats=3)"
+            nix \
+                --option run-diff-hook true \
+                --option diff-hook /etc/nix/diff-hook.sh \
+                --option enforce-determinism true \
+                --option repeat 3 \
+              build ".#$attr" --no-link --rebuild --keep-failed
+            if [[ "$?" = "1" ]]; then
+              echo "Failed report. Diff from 'diffoscope' below:"
+              cat /tmp/report.txt
+              mv /tmp/report.txt /tmp/report-$attr.txt
+            else
+              rm -f /tmp/report.txt
+            fi
+          done < result/nix-refs
+          echo "\nDone."
